[bot]
# 账号 必填
account = 0
# 密码 选填
password = ""
# SignServer 必填
signServer = "https://sign.lagrangecore.org/api/sign/39038"

[log]
# 日志级别: 可选 debug, info, warn, error
level = "info"
# 是否启用文件输出 (true = 输出到文件, false = 只输出到控制台)
enableFile = true
# 日志文件路径
filePath = "logs/app.log"
# 单个日志文件最大大小 (单位: MB)
maxSize = 10
# 保留的旧文件个数 (超过后会删除最旧的文件)
maxBackups = 20
# 保留的旧文件天数 (超过后会自动删除)
maxAge = 30
# 日志格式: 可选 text, json
format = "text"

[other]
qrCodePath = "crcode.png"
ginPort = 5562
# 允许连接的 ip，用于确保安全，为空时禁用白名单(不建议)
allowedIPs = [
    "127.0.0.1",
    "192.168.1.100",
    "10.0.0.1"
]
# 允许对bot进行关键操作（如回档等命令）的QQ号 示例 [114514,778899] 不输入则允许所有人
allowedUIDs = []
# 允许的群聊群号 示例 [1145145,7777666] 为空时监听所有群聊消息
allowedGroups = []
# 绑定饥荒联机版的群聊列表 示例 [1145145,7777666] 
# 请注意！！！必须配置此项，饥荒联机版的消息才会转发到配置中的群聊！！！
bindGroups = []